version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  kibana:
    image: kibana:7.17.1
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"

